model:
  dim: 128
  layers: 6
  heads: 8
training:
  epochs: 20
  ctx: 64
  imag_h: 15
  gamma: 0.99
  lam_return: 0.95
  lam: 0.1
dataset:
  base_dir: atari
  collect_steps: 10000
  reso: 84
  shard: 1000
tasks:
  train:
    - Phoenix
    - Phoenix
    - Phoenix
  eval: Phoenix
